name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2] # Adjust this number for more parallel jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (parallel)
        run: |
          npx cypress run \
            --record \
            --key ${{ secrets.CYPRESS_RECORD_KEY }} \
            --parallel \
            --ci-build-id ${{ github.run_id }}-${{ github.run_attempt }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ matrix.containers }}
          path: cypress/reports/mochawesome/ 